steps:
# Budowanie obrazu Docker
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/beauty-salon:$COMMIT_SHA', '.']

# Publikowanie obrazu w Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/beauty-salon:$COMMIT_SHA']

# Wdrażanie do Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'run', 'deploy', 'wiktoriabeuty',
    '--image', 'gcr.io/$PROJECT_ID/beauty-salon:$COMMIT_SHA',
    '--region', 'europe-west1',
    '--platform', 'managed',
    '--allow-unauthenticated'
  ]